#!/usr/bin/env bash
#
# DBBASIC Object Server — single-VM installer for Debian/Ubuntu.
#
# What it does (idempotent — safe to re-run):
#   - installs python3, venv, pip, git
#   - creates the `dbbasic` service user and the standard directory layout
#   - clones (or reuses) the server under /opt/dbbasic-object-server
#   - builds a virtualenv and installs the server
#   - writes /etc/dbbasic-object-server.env with a freshly generated admin
#     token (only if the file does not already exist — never overwrites yours)
#   - installs and starts a systemd unit bound to 127.0.0.1:8001
#   - runs the filesystem checker and a health check
#
# What it deliberately does NOT do (these are short, deliberate follow-ups
# printed at the end, and covered in docs/quickstart.md):
#   - create your admin user / turn on password login
#   - enable source writes, file writes, or package installs
#   - configure a public domain / TLS proxy
#
# Read it before you run it. Then:  sudo bash scripts/install.sh
#
set -euo pipefail

REPO_URL="${DBBASIC_REPO_URL:-https://github.com/askrobots/dbbasic-object-server.git}"
CODE_DIR="${DBBASIC_CODE_DIR:-/opt/dbbasic-object-server}"
STATE_DIR="${DBBASIC_STATE_DIR:-/var/lib/dbbasic-object-server}"
ENV_FILE="${DBBASIC_ENV_FILE:-/etc/dbbasic-object-server.env}"
UNIT_FILE="/etc/systemd/system/dbbasic-object-server.service"
SERVICE_USER="dbbasic"

say() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m warn:\033[0m %s\n' "$*"; }

if [[ "${EUID}" -ne 0 ]]; then
  echo "Run as root:  sudo bash scripts/install.sh" >&2
  exit 1
fi

say "Installing system packages"
apt-get update -qq
apt-get install -y -qq python3 python3-venv python3-pip git

say "Creating service user and directory layout"
if ! id "${SERVICE_USER}" >/dev/null 2>&1; then
  useradd --system --home "${STATE_DIR}" --shell /usr/sbin/nologin "${SERVICE_USER}"
fi
mkdir -p "${CODE_DIR}" "${STATE_DIR}/objects" "${STATE_DIR}/data"
chown -R "${SERVICE_USER}:${SERVICE_USER}" "${CODE_DIR}" "${STATE_DIR}"
chmod 755 "${CODE_DIR}"
chmod 750 "${STATE_DIR}" "${STATE_DIR}/objects" "${STATE_DIR}/data"

say "Fetching server code into ${CODE_DIR}"
if [[ -d "${CODE_DIR}/.git" ]]; then
  sudo -u "${SERVICE_USER}" git -C "${CODE_DIR}" pull --ff-only
else
  sudo -u "${SERVICE_USER}" git clone "${REPO_URL}" "${CODE_DIR}"
fi

say "Building virtualenv and installing the server"
if [[ ! -x "${CODE_DIR}/.venv/bin/python" ]]; then
  sudo -u "${SERVICE_USER}" python3 -m venv "${CODE_DIR}/.venv"
fi
sudo -u "${SERVICE_USER}" "${CODE_DIR}/.venv/bin/python" -m pip install -q --upgrade pip
sudo -u "${SERVICE_USER}" "${CODE_DIR}/.venv/bin/python" -m pip install -q -e "${CODE_DIR}[server]"

if [[ -f "${ENV_FILE}" ]]; then
  warn "${ENV_FILE} already exists — keeping it (admin token unchanged)"
else
  say "Writing ${ENV_FILE} with a freshly generated admin token"
  ADMIN_TOKEN="$("${CODE_DIR}/.venv/bin/python" -c 'import secrets; print(secrets.token_urlsafe(32))')"
  cat > "${ENV_FILE}" <<EOF
# Generated by scripts/install.sh. Edit deliberately; restart the service after changes.
DBBASIC_OBJECTS_DIR=${STATE_DIR}/objects
DBBASIC_DATA_DIR=${STATE_DIR}/data
DBBASIC_BACKUPS_DIR=${STATE_DIR}/data/backups
DBBASIC_PACKAGES_DIR=${CODE_DIR}/packages
DBBASIC_ADMIN_TOKEN=${ADMIN_TOKEN}

# First-boot posture: writes and public code execution stay closed until you
# have login, backups, and proxy access confirmed. Turn these on deliberately
# (see docs/quickstart.md and docs/single-vm-deployment.md).
DBBASIC_ENABLE_SOURCE_WRITES=false
DBBASIC_ENABLE_FILE_WRITES=false
DBBASIC_ENABLE_PACKAGE_INSTALLS=false
DBBASIC_ENABLE_PACKAGE_RESTORE=false
DBBASIC_ENABLE_PASSWORD_LOGIN=false
DBBASIC_COOKIE_SECURE=true

# Permissions start in the open; move to audit, then enforcement, once a
# policy and login are in place (docs/permissions-model.md).
DBBASIC_ENABLE_PERMISSION_AUDIT=false
DBBASIC_ENABLE_PERMISSION_ENFORCEMENT=false

# Conservative traffic and safety limits.
DBBASIC_MAX_REQUEST_BYTES=1048576
DBBASIC_MAX_CONCURRENT_REQUESTS=64
DBBASIC_MAX_CONCURRENT_EXECUTIONS=8
DBBASIC_OBJECT_TIMEOUT_SECONDS=5
DBBASIC_RATE_LIMIT_REQUESTS=1000
DBBASIC_RATE_LIMIT_WINDOW_SECONDS=60
DBBASIC_RATE_LIMIT_TRUST_PROXY_HEADERS=true
DBBASIC_LOGIN_LOCKOUT_ATTEMPTS=5
DBBASIC_LOGIN_LOCKOUT_WINDOW_SECONDS=900
DBBASIC_ENABLE_REALTIME=true
EOF
fi
chown root:"${SERVICE_USER}" "${ENV_FILE}"
chmod 640 "${ENV_FILE}"

say "Installing systemd unit"
cat > "${UNIT_FILE}" <<EOF
[Unit]
Description=DBBASIC Object Server
After=network-online.target
Wants=network-online.target

[Service]
User=${SERVICE_USER}
Group=${SERVICE_USER}
WorkingDirectory=${CODE_DIR}
EnvironmentFile=${ENV_FILE}
ExecStart=${CODE_DIR}/.venv/bin/uvicorn object_server:app --host 127.0.0.1 --port 8001 --no-access-log
Restart=on-failure
RestartSec=2
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=full
ReadWritePaths=${STATE_DIR}

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable --now dbbasic-object-server

say "Running filesystem checks"
set -a; . "${ENV_FILE}"; set +a
( cd "${CODE_DIR}" && .venv/bin/python -m deployment_checks ) || warn "deployment_checks reported issues (see above)"

say "Health check"
sleep 2
if curl -fsS http://127.0.0.1:8001/health >/dev/null; then
  say "Server is up on 127.0.0.1:8001"
else
  warn "Health check failed — see: journalctl -u dbbasic-object-server -e"
fi

cat <<EOF

$(printf '\033[1;32mInstalled.\033[0m') Next, deliberate steps (docs/quickstart.md):

  1. Create your admin user and turn on login:
       cd ${CODE_DIR}
       sudo -u ${SERVICE_USER} DBBASIC_DATA_DIR=${STATE_DIR}/data \\
         .venv/bin/python object_identity_cli.py create-superuser --user-id you --email you@example.com
       # then set DBBASIC_ENABLE_PASSWORD_LOGIN=true in ${ENV_FILE} and:
       sudo systemctl restart dbbasic-object-server

  2. Put a domain and TLS in front (Caddy), then enable package installs to
     add apps. Your admin token is in ${ENV_FILE} (DBBASIC_ADMIN_TOKEN).

  Watch logs:   journalctl -u dbbasic-object-server -f
EOF
